[project]
name = "vivienda-slp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.6",
    "notebook>=7.4.7",
    "pandas>=2.3.3",
    "pyarrow>=21.0.0",
]
